name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v3
      - name: Install claat
        run: go install github.com/googlecodelabs/tools/claat@latest
      - name: Generate lab contents
        run: $HOME/go/bin/claat export -o docs/ja workshop.ja.md
      - name: Move directory
        run: mv docs/ja/docs/* docs/ja
      - name: Generate lab contents for EN
        run: $HOME/go/bin/claat export -o docs/en workshop.en.md
      - name: Move directory
        run: mv docs/en/docs/* docs/en
      - name: Move index
        run: mv index.html docs/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/
